### ISSUE TITLE
haplotyping failures

### ISSUE THREAD

**Issue by hirokomatsui** [gaow/SEQLinkage#1]
Hi,

Thank you for providing the great tool!
I've seen the error message from seqlinkage:

ERROR: 2,211 regional markers failed to be generated due to haplotyping failures!

What is the case of this?

**Comment by gaow** [comment]
Hi Hiroko,

Sorry to hear that problem. It sounds like a systematic problem considering over 2000 regions failed. So very much likely it is debuggable. It would be great if you could email me privately a test data so that I can try to replicate and fix. Thanks!

**Comment by gaow** [comment]
@hirokomatsui Although without a reproducible example I cannot figure out the problem, we do have now updated the docker image for the program using latest refGene database:

http://bioinformatics.org/seqlink/installation

Other users don't seem to have an issue with at least this release. I'm closing this ticket for now.
