### ISSUE TITLE
Haplotyping erro

### ISSUE THREAD

**Issue by dheerajbobbili** [gaow/SEQLinkage#11]
Hi,

I am trying to use Seqlinkage to perform linkage analysis of whole genome sequencing data. 
 Below is the command that I used.

$SEQLINK --fam test.fam --vcf vcfs/test.rsids.vcf.gz --chrom-prefix chr --moi AD --run-linkage --wt-pen 0.00001 --mut-pen 1.0 --prevalence 0.0001

 Here is the log

MESSAGE: 1 samples in VCF file will be ignored due to absence in FAM file
MESSAGE: 1 families with a total of 4 samples will be scanned for 25,305 pre-defined units
MESSAGE: 0 units (from 3,107,622 variants) processed; 0 Mendelian inconsistencies and 0 recombination events handled
MESSAGE: 2,928 units ignored due to absence in VCF file
MESSAGE: 248 units ignored due to absence of variation in samples
ERROR: 22,129 regional markers failed to be generated due to haplotyping failures!
MESSAGE: Archiving regional marker data to directory
 [test/cache]
MESSAGE: 0 units will be converted to LINKAGE format
MESSAGE: 0 units successfully converted to LINKAGE format
MESSAGE: Archiving LINKAGE format to directory
 [test/cache]
MESSAGE: Linkage analysis succesfully performed for 0 units
MESSAGE: Reports in html format generated

Here is the error,

**ERROR: 22,129 regional markers failed to be generated due to haplotyping failures!**

Am I missing something??

Dheeraj

**Comment by gaow** [comment]
@dheerajbobbili sorry for the very late reply. Although without a reproducible example I cannot figure out the problem, we do have now updated the docker image for the program using latest refGene database: 

http://bioinformatics.org/seqlink/installation

Other users don't seem to have an issue with at least this release. I'm closing this ticket for now.
