### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by josemq** [gaow/SEQLinkage#14]
Hi,

I'm getting the following error when compiling on Debian 9. No libraries get created..

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

please help.

**Comment by josemq** [comment]
Also getting this error in the beginning of compiling:

src/HaplotypingUtils.cpp:210:28: error: call of overloaded ‘div(unsigned int&, unsigned int&)’ is ambiguous
  div_t divresult = div(n, a);

**Comment by gaow** [comment]
SEQLinkage is best executed with Docker. Docker image for `SEQLinkage` and instruction to run `SEQLinkage` from docker has been updated [here](http://bioinformatics.org/seqlink/installation).

**Comment by gaow** [comment]
Hopefully [this](https://github.com/gaow/misc/blob/master/docker/debian-py2.dockerfile) and [this](https://github.com/gaow/misc/blob/master/docker/seqx.dockerfile) docker files can give you some insights on how exactly SEQLinkage is compiled.
