### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alyssaclay** [gaow/SEQLinkage#15]
The software is lovely and I look forward to citing it in our publication. I am in the midst of using SEQLinkage software for whole exome sequencing data I have on a number of affects and unaffecteds within families- I do not have sequencing data on all the family members in each family. My question is regarding the input files: vcf and Fam. Does the fam file have to match the vcf file? As I stated we have large family information but only some in the family are sequenced. If they do have to match then what is the best way for me to add dummy columns on to the Vcf? Ie to match the fam file (maintaining family structure but having ./. In place for none sequenced individuals.  Please let me know if there is a better place to post this question as the documentation guided me here. Thank you.

**Comment by gaow** [comment]
Sorry for the delayed reply but if you run SEQLinkage you'll see it uses samples that exist in both FAM and VCF files, matched by sample names. It will report on screen those samples that exist in FAM file but not in VCF.
