### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by bobbyljones** [gaow/SEQLinkage#16]
On a macOS 10.12.6 box, I'm trying to run the example but I get
ERROR: Cannot find file [/Users/administrator/Desktop/SEQLinkage/seqlinkage-example/seqlinkage-example.vcf.gz]!
The command is:
administrators-Mac-Pro:seqlinkage-example administrator$ seqlink --fam seqlinkage-example.fam --vcf seqlinkage-example.vcf.gz -f MERLIN 
The alias is setup as indicated in the instructions:
seqlink='docker run --rm --security-opt label:disable -v ${HOME%%/${USER}}:/home -v /tmp:/tmp -t -P -w $PWD -u $UID:${GROUPS[0]} gaow/seqx seqlink'

**Comment by gaow** [comment]
Hi @bobbyljones sorry for the troubles. Could you try again with:

```
alias seqlink='docker run  --rm--security-opt label:disable -t '\
'-P -h SEQLINK -w $PWD -v $HOME:/home/$USER -v /tmp:/tmp -v $PWD:$PWD '\
'-u $UID:${GROUPS[0]} -e HOME=/home/$USER -e USER=$USER gaow/seqx seqlink'
```

**Comment by bobbyljones** [comment]
That worked. Thanks, B.

**Comment by bobbyljones** [comment]
Ok, that worked. I closed the issue. Thanks, B.

**Comment by bobbyljones** [comment]
Unfortunately now I'm getting

*MESSAGE: Checking local resources 1/5 ...*/bin/sh: 1: wget: not found


*ERROR: Failed to download genemap.txt*

*MESSAGE: Checking local resources 2/5 ...*/bin/sh: 1: wget: not found

*ERROR: Failed to download mlink*

*MESSAGE: Checking local resources 3/5 ...*/bin/sh: 1: wget: not found

*ERROR: Failed to download unknown*

*MESSAGE: Checking local resources 4/5 ...*/bin/sh: 1: wget: not found

*ERROR: Failed to download makeped*

*MESSAGE: Checking local resources 5/5 ...*/bin/sh: 1: wget: not found

*ERROR: Failed to download pedcheck*
I thought the problem might be on my end but wget and sh are in
/sw/bin/wget and /bin/sh respectively. B.

**Comment by gaow** [comment]
@bobbyljones sorry this bug was introduced in a recent upgrade of the docker image. I just built a new docker image which I think should fix it. Would you please `docker pull gaow/seqx` and try again? 

BTW thanks for the pointer of the out-dated documentation. I've updated the docker alias:

http://bioinformatics.org/seqlink/installation

**Comment by bobbyljones** [comment]
We appear to be in good shape now. Thanks for your help. B.
