### ISSUE TITLE
"haplotyping failures"

### ISSUE THREAD

**Issue by Chitanda-Satou** [gaow/SEQLinkage#18]
Dear author, thanks for this awesome software.
I have generate a VCF using :
![图片](https://user-images.githubusercontent.com/32410912/74043884-1ec8f600-4a05-11ea-8fe9-0d9e29a6e9ee.png)
Then, the VCF file was bgzipped, and I generate a pedigree file, but when running seqlink to get MERLIN files, an ERROR occured like:
![图片](https://user-images.githubusercontent.com/32410912/74043730-df020e80-4a04-11ea-8d2d-ab9d87568512.png)

Do you have some clues for checking what's wrong?

Thanks!

**Comment by gaow** [comment]
@Chitanda-Satou there seems to be lots of mendelian inconsistencies detected -- could you double check if your input genotype matches the family relationship specification in your pedigree file?

**Comment by Chitanda-Satou** [comment]
Thanks a lot, dear @gaow . I will check it.

**Comment by gaow** [comment]
@Chitanda-Satou please try the updated SEQLinkage docker image with instructions here:

http://bioinformatics.org/seqlink/installation

I have updated the gene definition using the latest refGene database (March 1, 2020 release). Please let me know if there is still an issue after the update.

**Comment by Chitanda-Satou** [comment]
Thanks for your nice reply! 

As your advice before, after correction of the pedigree file, SEQLinkage works.
I will test your new docker image later.

Anyway may I ask for your advice for this case below?

After running the pipeline of SEQLinkage and MERLIN, all LODs were found as 0, just like:
![image](https://user-images.githubusercontent.com/32410912/76922893-ed4d1f80-690c-11ea-8d4c-ea64967eab8d.png)
Is this **possible**? Or there **must** be someting wrong?

Thanks again @gaow ! SEQLinkage is really awesome.

**Comment by gaow** [comment]
@Chitanda-Satou if current version works for the haplotyping step please stick to it for now. There are a couple of other updates around the corner relevant to using external reference frequencies. We should have another version released later this week.

It's not impossible, by definition of LOD, that they equal zero in your data. But it is a bit odd if all of them are absolutely zero. I will try to analyze some data on my end later this week to rule out possible artifacts; then we'll see if it is some problems on your end.
