### ISSUE TITLE
obtaining genetic_pos_searcher

### ISSUE THREAD

**Issue by sjin09** [gaow/SEQLinkage#2]
Dear Wang,

I am trying to use the genetic_pos_searcher to generate a new blueprint file. I have seen in your documentation (last updated on May 8th 2014) that SEQlinkage uses RefSeq for the blueprint and I would like to use the annotations from Ensemble for creating the blueprint.

With the command that you have provided 

wget http://www.bioinformatics.org/seqlink/uploads/genetic_pos_searcher

I have only been able to obtain a log file with the error 

"You have a followed a link to a topic that doesn't exist yet. If permissions allow, you may create it by clicking on "Create This Page""

has the link been removed? and would it be possible to obtain the through another link?

Many Thanks,
Jin

**Comment by gaow** [comment]
Hi Jin,

Sorry that link has been fixed. It should in fact be `genetic_pos_searcher.py`. But now I made it consistent with what's on the doc. Just remember to run it in Python.

The code was written by a grad student from Leal Lab at Baylor College of Medicine. It uses simple linear interpolation using info from adjacent data points. Now on a second thought, I think it might work better to fit a LOWESS model with more data points in the neighborhood. Perhaps you can try to implement that based off what we have here.

Gao

**Comment by sjin09** [comment]
Dear Gao,

Thank you for your swift response!

I also wanted to ask some additional questions regarding the usage of SEQLinkage. I will be using the SEQLinkage to perform genome-wide linkage analysis of a pedigree with autosomal recessive form of Parkinson's disease. The paper that you have published deals explicitly with whole-exome data and I was wondering whether you have recommendations for collapsed SNPs in linkage disequilibrium for whole-genome data.

Many Thanks
Jin

**Comment by gaow** [comment]
@sjin09 Sorry for the very delayed reply as I'm going over unresolved tickets here. There is nothing magical about the region to be collapsed for linkage analysis -- just a matter of interpretation, which is easier in WES data than WGS data. For your case, I guess you can start with some sliding window definition you think reasonable for WGS data and use option `-b` to feed that information to SEQLinkage.
