### ISSUE TITLE
is there anything wrong with my fam file?

### ISSUE THREAD

**Issue by dzhang198707** [gaow/SEQLinkage#20]
is there anything wrong with my fam file? 
the SeqLink tell the next error information:
ERROR: Cannot find parents (OPMDGYQing3-2 and 0) of OPMDGQXin4-4 in [/home/dzhang01/daiyi/linkage/snp.linkage/10fam.fam]!
the following is my fam file.
1	OPMDGWZhen2-5	0	0	2	1
1	OPMDGWXia2-7	0	0	2	1
1	OPMDGWCai2-9	0	0	1	1
1	OPMDGWXiang2-11	0	0	1	1
1	OPMDGWChun2-12	0	0	1	0
1	OPMDGYQing3-2	0	0	1	2
1	OPMDGYZhu3-12	0	0	2	2
1	OPMDGYJie3-14	0	0	2	2
1	OPMDGQXin4-4	OPMDGYQing3-2	0	1	2
1	OPMDGQDong4-15	0	0	1	2

thanks in advance for your help.

**Comment by gaow** [comment]
@dzhang198707 indeed most of the parents ID (3rd and 4th columns of the FAM file) are missing. The only potentially usable sample for linkage analysis is `OPMDGQXin4-4` which has one parent information `OPMDGYQing3-2` but misses the other parent. This is not going to work for linkage analysis.

**Comment by dzhang198707** [comment]
> @dzhang198707 indeed most of the parents ID (3rd and 4th columns of the FAM file) are missing. The only potentially usable sample for linkage analysis is `OPMDGQXin4-4` which has one parent information `OPMDGYQing3-2` but misses the other parent. This is not going to work for linkage analysis.

**Comment by dzhang198707** [comment]
@gaow thanks for your prompt and valueble reply.
the attached is my pedigree structure.  i only have the genetic data for family members with red number.
may you help me check whether i can to do linakge analysis with it? if i can, how do i make the fam file?
thanks so much!
![家系图带数字](https://user-images.githubusercontent.com/22020765/86468922-f999a300-bd6a-11ea-8d62-21a3bcb1ef7d.jpg)

**Comment by gaow** [comment]
@dzhang198707 If you provide the full pedigree FAM file SEQLinkage might work -- it can handle missing genotypes. But it does not look like there is enough data for a significant LOD score to be obtained from parametric linkage. Alternatively, samples 12, 14 and 15 might allow you for doing some non-parametric linkage (https://github.com/statgenetics/rvnpl) but again there does not seem enough power in this data-set.

**Comment by dzhang198707** [comment]
thanks so much for your help and advices! I will have a try.
Thanks again!





Dingding Zhang

Central Research Laboratory, 

Peking Union Medical College Hospital,

Peking Union Medical College & Chinese Academy of Medical Sciences

No. 1 Shuaifuyuan,

Beijing, 100730, China

Tel: (+86) 188-1083-6586

On 07/03/2020 21:57, gaow wrote:

@dzhang198707 If you provide the full pedigree FAM file SEQLinkage might work -- it can handle missing genotypes. But it does not look like there is enough data for a significant LOD score to be obtained from parametric linkage. Alternatively, samples 12, 14 and 15 might allow you for doing some non-parametric linkage (https://github.com/statgenetics/rvnpl) but again there does not seem enough power in this data-set.

**Comment by gaow** [comment]
@dzhang198707 you are welcome! On a separate note, would you mind email me at wang.gao@columbia.edu for some additional info I'd like to share offline?
