### ISSUE TITLE
Is the line to normalize allele freq to 1?

### ISSUE THREAD

**Issue by changebio** [gaow/SEQLinkage#32]
https://github.com/gaow/SEQLinkage/blob/aa3f900feba45d2f778863c7d0df5e7cf2594027/source/Core.py#L933

`data.maf[item] = tuple(tuple(np.array(v) / np.sum(v)) if np.sum(v) else v for v in data.maf[item])`

I think the `if` condition is no right. Should it be `if np.sum(v)!=1`?

**Comment by gaow** [comment]
it's correct -- `if np.sum(v)` ensures that you dont accidentally divide it by zero.
