### ISSUE TITLE
the vcf file and the annotation file don't match

### ISSUE THREAD

**Issue by changebio** [gaow/SEQLinkage#34]
For example at chr19 56176048:
There are 3 variants in vcf. however, there are 4 in annotation(one of them is duplicated).
![Screen Shot 2022-02-16 at 2 13 14 PM](https://user-images.githubusercontent.com/10182773/154339769-97629392-46b1-4a4d-86ce-76b89e83b1b3.png)

**Comment by gaow** [comment]
Looks like we need some QC (remove exact duplicate) on the annotation file ... I am not sure how it happened in the first place. If it is the original ANNOVAR output it's out of our control.

**Comment by gaow** [comment]
> I am wondering how we merge the ANNOVAR output to the vcf file previously?

It was not straightforward: using `vtools import; vtools use; vtools output`. But there might be better ways after all these years? Even if that's the case I still think we should keep the information separate. 

> Besides, for the variants at 56176048, their orders are different between the vcf and the annotation.

The ref/alt should be the same if the same fasta reference is used. For SEQLinkage I suggest that we match with exact chr pos ref alt and generate a list of mismatches to warn users. I dont want to do anything smart when it's user's responsibility on input data

**Comment by changebio** [comment]
Fix by getting the common variants between vcf and annotation file.
