### ISSUE TITLE
ERROR: skipped line # (duplicate sample name '#' found!)

### ISSUE THREAD

**Issue by alyssaclay** [gaow/SEQLinkage#7]
I am attempting to use SEQLINKAGE for 2-point linkage analysis.
I have 50+ families and each family has unique familyIDs.
Individual IDs within the these families are obviously unique.
However, across families they are not.
This is not an issue for other linkage programs like MERLIN-because of the unique family they belong too.

I received this error multiple times : ERROR: skipped line # (duplicate sample name '#' found!)

I wanted to confirm that in seqlinkage every individual needs to have a unique individual ID? 
Regardless of the family ID being unique.

Thank you.
Alyssa
Post-doc
New to Linkage

**Comment by gaow** [comment]
This is very much likely an input format issue -- `#` cannot be a sample name. Perhaps your FAM file has a problem? I am going to close this ticket for now but please let me know if this question is still relevant and that you are sure FAM file is correct.
