### ISSUE TITLE
Problem running docker

### ISSUE THREAD

**Issue by pladijs** [gaow/SEQLinkage#8]
I installed seqlinkage through the docker application, and when trying to run with the command listed on the website it says 
"docker run -v $PWD:/home/seqx/data gaow/seqx seqlink --fam pedigree.fam --vcf variants.vcf.gz -f MERLIN
ERROR: Cannot find file [/home/seqx/data/variants.vcf.gz]!"
I tried adding such a folder and moving my vcf but it still shows the error.

**Comment by omerfaruk84** [comment]
Try this way:  docker run -v //c/Seqlink:/home/seqx/data gaow/seqx seqlink --fam test.fam --vcf test.vcf.gz --freq AF -o LinkageHSP122 -j 2 --moi AR -K 0.001 -W 0 -M 1 --run-linkage

C:/Seqlink folder is the folder where I keep the VCF files. Docker uses C/Seqlink folder as a mirror of (home/seqx/data) docker folder.

**Comment by gaow** [comment]
Docker image for `SEQLinkage` and instruction to run `SEQLinkage` from docker have been updated [here](http://bioinformatics.org/seqlink/installation).
